= Pylar

An open-source hardware (OSHW) aerobic composting project, modeled as a http://mach30.github.io/dof[DOF] component.

== View the documentation locally

You can build the documentation site on a local desktop:

=== Installing requirements

You will need https://git-scm.com/[git] to clone the project contents and https://www.docker.com/[docker] to run the docker image that contains the dependencies needed for building the documentation.

1. Docker
2. Git (for contributors, quicker access to the repository source code)
3. A Bash terminal (standard terminal environment for *nix and macOS).

NOTE: To Windows users: Windows Command Prompt will not satisfy this dependency. Instead, you can use PowerShell or another Bash terminal (like Git Bash for example).

=== Cloning the repo

Clone the https://github.com/pylar-io/pylar[pylar repo]. Don't forget to use `--recurse-submodules` flag, or else you won't pull down some of the code you need to generate a working site.

[source,bash]
----
git clone --recurse-submodules https://github.com/pylar-io/pylar.git
cd pylar
----

Note: If you accidentally cloned without using `--recurse-submodules`, you can run `git submodule update --init --recursive` to pull down submodules needed to generate a working site.

=== Building the documentation

Once you've cloned the repo & installed docker, run the `buildDocs.sh` script in the project root directory (Note: Linux users may need to prepend this command `sudo`). This will build a docker image, as well as install node modules, needed for generating the `pylar` page locally. You can view all locally installed docker images by running `docker images`.

[source,bash]
----
./buildDocs.sh
----

Once you run this step, you can locally view the documentation by opening `dist/index.html` in a web browser or by opening `dist/pylar-architecture.pdf` in a pdf viewer.
